# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"
early_access: true

# Inherit settings from compass-brand parent
inheritance: true

chat:
  auto_reply: true

reviews:
  profile: "assertive"
  request_changes_workflow: false
  high_level_summary: true
  poem: false
  review_status: true
  commit_status: true
  collapse_walkthrough: false
  changed_files_summary: true
  sequence_diagrams: true

  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - main
      - develop
    ignore_title_keywords:
      - "WIP"
      - "DO NOT MERGE"
      - "[skip review]"

  tools:
    ruff:
      enabled: true
    shellcheck:
      enabled: true
    gitleaks:
      enabled: true
    markdownlint:
      enabled: true

  path_filters:
    - "!**/node_modules/**"
    - "!**/.venv/**"
    - "!**/dist/**"
    - "!**/build/**"
    - "!**/poetry.lock"
